version: '3'

services:
  php:
    image: php:7.4-fpm-alpine3.15
    container_name: php
    networks:
      - mynet
    volumes:
      - ./website_app/:/var/www/html/
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - mynet
    volumes:
      - ./website_app/:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/wp.freeda-francis.tech.crt:/etc/nginx/cert.crt
      - ./certs/wp.freeda-francis.tech.key:/etc/nginx/cert.key
    restart: always
    ports:
      - "80:80"
      - "443:443"
networks:
  mynet:
